### ISSUE TITLE
High time latency in retriever inference

### ISSUE THREAD

**Issue by swaggy-TN** [facebookresearch/DPR#101]
Hi,
I ran dense_retriever.py and according to the log, it takes the machine about 1587 seconds to find top-100 docs for only 2000 questions. But I think in your paper, you claim that it can index 995 question per sec. I have no idea why...

**Comment by vlad-karpukhin** [comment]
Hi,
This is because it uses exhaustive search (flat index) by default.
The lossy and fast index we mentioned in the paper (HNSW) indeed retrieves results in a portion of a second but takes about 9 hours to create the index and takes extra ~160GB of RAM.
You can enable it with --hnsw_index param.
But using the flat index is still much faster for research purposes, when you need to retrieve for a relatively small amount of questions only once(< ~1 million).

**Comment by swaggy-TN** [comment]
OK, thanks for the reply.
