### ISSUE TITLE
Question about transformers version

### ISSUE THREAD

**Issue by avikpal00** [facebookresearch/DPR#106]
Hello,
Will the package be updated for transformers>=4.0 ?

**Comment by vlad-karpukhin** [comment]
Hi @avikpal00 ,
I don't plan to upgrade transformers as of now. But can do that later, I'm to provide some major updates for this codebase including new (improved) checkpoints in a couple of upcoming weeks

**Comment by avikpal00** [comment]
Hi @vlad-karpukhin thanks for the update.
Also, I tried some workarounds to get it to work for latest transformer version. Modified init.py to change importlib.util.find_spec("transformers"), updated the transformer import classes in hf_models.py and set strict=False when loading state dict of old encoder checkpoint. I am stuck with this error now -

![image](https://user-images.githubusercontent.com/72965135/109764376-78f0b680-7c19-11eb-8bdc-ba18d9638f16.png)

I am currently using checkpoint.retriever.single.nq.bert-base-encoder. Will training the retriever again to get new checkpoint be of any help here?

**Comment by calderma** [comment]
Hello, there's actually only a few lines of code that you need to change in order to get it to work with transformers>=4.0. Just change the file dpr/models/hf_models.py by changing the imports.
from:
from transformers.modeling_bert import BertConfig, BertModel
from transformers.optimization import AdamW
from transformers.tokenization_bert import BertTokenizer
from transformers.tokenization_roberta import RobertaTokenizer
to:
from transformers import BertConfig, BertModel
from transformers import AdamW
from transformers import BertTokenizer
from transformers import RobertaTokenizer

and pass "return_dict=False" in the HFBertEncoder class's forward method. I don't know if there's other things that need to be changed but it works for me and gives good results.

**Comment by vlad-karpukhin** [comment]
Hi @calderma ,
Thank you for the instructions.
It would be great if you can update this codebase. I may not be able make these changes for quite some time.

**Comment by calderma** [comment]
I can do that but it will make it incompatible with transformers <4.0

**Comment by calderma** [comment]
cool i'll submit that in the next week or two.

**Comment by vlad-karpukhin** [comment]
UPD: changing only import statements won't be enough, one needs to update the output results handling:
the result is now BaseModelOutputWithPoolingAndCrossAttentions object, or a dict instead of a tuple like before but there are some (v>4.x only) input flags to request specific output.

**Comment by fmguler** [comment]
Hi, any update on this? 
Currently DPR requires transformers 3.1.0 and that requires tokenizers 0.8.1.rc2 which cannot be installed with Python 3.9 pip.

**Comment by vlad-karpukhin** [comment]
Hi @fmguler , I have an update for HF 4.x version, will try to ship it in the next 2 weeks

**Comment by vlad-karpukhin** [comment]
Hi @fmguler , I've updated the code for HF v4.3 (that was the version it was tested on), but should be fine for higher versions as well. Please check.

**Comment by fmguler** [comment]
Amazing! Thank you very much @vlad-karpukhin
