### ISSUE TITLE
Prediction Ratio of Multi Node Training

### ISSUE THREAD

**Issue by robinsongh381** [facebookresearch/DPR#112]
Hello !

I have been training the retrieval model with multi-node (two nodes) setting and the `correct prediction ratio` looks weird.
 - Under single node, the `correct prediction ratio`started with **80** ish at epoch 0 and increased gradually and reached **85** ish around 10 epoch.
 - However, under multi node, the `correct prediction ratio` started with **40** ish and increased gradually and reached **45** ish around 10 epoch.

I suspect that during the computation of `correct prediction ratio` , only one node is reflected hence it is almost half of  the case for single node.

Have you tried with multi-node environment ?
Thanks

**Comment by robinsongh381** [comment]
@vlad-karpukhin 
Alright, that sounds fair enough.
Having said that, relatively low value of `correct prediction ratio `during training under multi-node setting DOES NOT mean the trained model would perform bad for dev dataset. 

Am I correct ?
Cheers

**Comment by vlad-karpukhin** [comment]
Hi @robinsongh381 ,
1."Having said that, relatively low value of correct prediction ratio during training under multi-node setting DOES NOT mean the trained model would perform bad for dev dataset.

Am I correct ?"

Correct but we found effective batch size of 128 (x2 if count hard negatives) to be the best setting. Running on just 2 nodes will results in rather inferior model performance at the end.

2."How can I effectively run with multi-node ?"

generate_dense_embeddings.py is embarrassingly parallel tool. It is probably the best to run separate shards on different gpus (1-2 is fine) instead of running a single instance on multiple gpus. A big portion of the processing time is spent on data processing which happens in cpu and the gains from using multiple gpus are not that big.
