### ISSUE TITLE
QA Dataset Download Link

### ISSUE THREAD

**Issue by NoviScl** [facebookresearch/DPR#143]
Hi,

May I check where can I download the data for WebQuestions and CuratedTREC that you used in the paper?

**Comment by vlad-karpukhin** [comment]
Just uploaded them & added to the configuration

See these commits for resource/config names:
https://github.com/facebookresearch/DPR/commit/971aafdc710e625d82f5b77874addf98b1ac6799
https://github.com/facebookresearch/DPR/commit/74fd351726f0f0326dfff89aa2a36ca16c0da832
https://github.com/facebookresearch/DPR/commit/524532805f27102d3f190626d22d7a2835a5bd39

Please note that CuratedTREC dataset validation requires regexp matching instead of exact answer matching, so you should set match=regex when running dense_retriever for its results evaluation

**Comment by yeliu918** [comment]
Hi,

I didn't find the "data.retriever.curatedtrec-dev" in this uploaded resource. 
![image](https://user-images.githubusercontent.com/20387632/117359314-d48b2a80-ae7c-11eb-8541-1ed4ec1edf61.png)

**Comment by vlad-karpukhin** [comment]
Just added.

**Comment by yeliu918** [comment]
Why the number of dev samples of both datasets is smaller than the paper reported? 
The one in "data.retriever.webq-dev" is 278, while the paper is 341. 
The one in "data.retriever.curatedtrec-dev" is 116, while the paper is 133.
