### ISSUE TITLE
About sampling on positive and negative passages in the DPR reader

### ISSUE THREAD

**Issue by Yifan-Gao** [facebookresearch/DPR#24]
In the training of reader model, a passage selection score is computed over $[p_1, p_2, ..., p_24]$ in your implementation. But I find that the positive passage will always be put as $p_1$ (see `switch_labels`)

https://github.com/facebookresearch/DPR/blob/d7ba973ab2d862d1b44c2402b59b1ca2a362ee96/dpr/models/reader.py#L78-L80

Will this introduce some bias in the training stage? The model will tend to take the first passage from retriever as the positive one, which might make the rerank less effective.

**Comment by shmsw25** [comment]
Hi @Yifan-Gao, thanks for your interest, and great question. It actually doesn't introduce bias because we don't use index information in the objective function. Randomly assigning the positive passage (or any kind of different ways to assign the positive passage) will not change the loss value. It's only for the simplicity of the code that we always use $p_1$ for positive passage.

**Comment by Yifan-Gao** [comment]
I see. Yes, I did not realize this point when I posted this issue. Thanks for your reply.
