### ISSUE TITLE
Limited number of passages for the Reader

### ISSUE THREAD

**Issue by iftachg** [facebookresearch/DPR#29]
Looking at the preprocessed NQ data files for the reader module I see that the number of passages per question varies between 5 and 100 with an average of 57 passages per question. Can you share why this is so?

**Comment by vlad-karpukhin** [comment]
Hi, 

That is because we used a specific positive and negative passages filtering heuristics. You can find the details in this method.
https://github.com/facebookresearch/DPR/blob/master/dpr/data/reader_data.py#L103
There are a lot of adjustable parameters (https://github.com/facebookresearch/DPR/blob/master/dpr/data/reader_data.py#L95).

We didn't experiment much with them, there is probably a better configuration set.

**Comment by vlad-karpukhin** [comment]
seems this can be closed now
