### ISSUE TITLE
Can not reproduce retriever results on NQ dataset.

### ISSUE THREAD

**Issue by shaonan1993** [facebookresearch/DPR#32]
Hi, thanks for sharing the source code!

I'm trying to reproduce retriever results on NQ dataset. I use the similar hyper-parameters but the final average rank is 93 (it should be 25 as readme.md said). I only change the nproc_per_node to 2 for device limited? Both val_av_rank_hard_neg and val_av_rank_other_neg is 30 as default.

**Comment by vlad-karpukhin** [comment]
Hi,
What is your effective batch size? How many gpus and servers do you use?
 average rank works differently depending on these parameters and so the final number may be quite different.

**Comment by shaonan1993** [comment]
> Hi,
> What is your effective batch size? How many gpus and servers do you use?
> average rank works differently depending on these parameters and so the final number may be quite different.

I use 2 V100/32G gpus on single machine to train the model, batch size is 16 for each gpu.

**Comment by vlad-karpukhin** [comment]
Hi,
using 2 gpus in DDP mode will give your different av rank compared to our x8 gpu setup since this validation type computes its own 'shard' extracted as a part of all the data per process. 
In your case - 2 'shards' will split dataset to much larger chunks of data  than that for x8 gpu split and it is quite expected that your av.rank is worse.
So you should not compare them directly, BUT what matters is that your effective bath size 2x16=32 vs 8x16=128 in our setup and that will affect the quality of the model your train in a negative way.
Unfortunately, DPR retriever training depends in batch size and if you want to train a models with comparable to our results, you should have enough gpus for that.

**Comment by shaonan1993** [comment]
OK～I got it.

Thank you for answering.
