### ISSUE TITLE
Number of passages for each question used in Table 5 of DPR paper

### ISSUE THREAD

**Issue by antoniolanza1996** [facebookresearch/DPR#46]
Hi @vlad-karpukhin,
Thanks for sharing your work on GitHub.

I have a question regarding your End-to-End QA setup used to obtain EM values reported in **Table 5** of the paper:
What is the number of retrieved passages (for each question) by the retriever component which are then passed to the reader component?
Have you used the top-100? Or have you changed this number?
Thanks

**Comment by vlad-karpukhin** [comment]
Hi Antonio,

Yes we used top 100 results but also tried top 200 without much difference in end to end numbers.
But there is an extra data preprocessing step for NQ since it has gold passages evidence.

It happens here https://github.com/facebookresearch/DPR/blob/master/dpr/data/reader_data.py#L103
and requires data.gold_passages_info.nq_* resources to be properly processed.

If you don't provide --gold_passages_src & --gold_passages_src_dev, it won't apply a set of heuristics and e2e numbers will be lower than what we reported.

**Comment by antoniolanza1996** [comment]
@vlad-karpukhin  all right, thanks for your detailed explanation.

I have another question: even though DPR retrievers are trained only with english data, have you tried experiments with other languages (e.g. multilingual, German, Italian) or have you already planned to do them in the future?
Do you have some advices for using DPR in a different language other than english?

**Comment by vlad-karpukhin** [comment]
You need a good multi-lingual (or your specific language) pre-trained BERT/Roberta models and then finetune DPR on top of them.
Please have a look HF's pre-trained models list:
https://huggingface.co/transformers/pretrained_models.html
Since DPR uses HF's models, looks like you just need to use the multi-lingual version from HF and re-train DPR.

We don't plan that at the moment. 
Also, I have seen some general purpose IR models trained with multiple languages in mind recently like this one https://arxiv.org/abs/1907.04307.

**Comment by antoniolanza1996** [comment]
Thank you very much for the support. I will consider your advices.
