### ISSUE TITLE
Retrieval results for TriviaQA

### ISSUE THREAD

**Issue by yuyuz** [facebookresearch/DPR#50]
The retrieval results for NQ seems to be stored in `data.retriever_results.nq.single.train/dev/test`. But I couldn't find the retrieval results for TriviaQA. Could you specify how to access that? Thanks.

**Comment by vlad-karpukhin** [comment]
Hi Yuyu, 
Unfortunately, we don't provide similar results for Trivia since our best for that dataset comes from our hybrid retrieval approach where we used both bm25 retrieval system (Lucene) and dense embeddings.
Instead, we only provide final hybrid results converted into serialized format for the reader training. See data.reader.trivia.multi-hybrid.train download resource.

**Comment by yuyuz** [comment]
Thanks Vladimir for the detailed explanation!
