### ISSUE TITLE
Requesting encoded wikipedia files using checkpoint.retriever.multiset.bert-base-encoder

### ISSUE THREAD

**Issue by vaibhavad** [facebookresearch/DPR#59]
Hi, thank you for open-sourcing DPR and providing pre-trained models!

Is it possible to provide encoded Wikipedia files using checkpoint.retriever.multiset.bert-base-encoder?

**Comment by vlad-karpukhin** [comment]
Hi,
We don't have it as the moment in the required format and also we didn't plan to host expensive embeddings which provides basically same performance as NQ only trained model. Can you use that one?
Since we are working on a stronger version on the retrieval model right now, I unfortunately don't have bandwidth to regenerate the multiset version at this moment.

**Comment by vaibhavad** [comment]
Sure, that makes sense. I'll continue using the embeddings generated from NQ only trained model. Thanks!

**Comment by morningmoni** [comment]
Hi @vlad-karpukhin,

I tried both `multiset/bert-base-encoder.cp` and `single/nq/bert-base-encoder.cp` using the `wiki_passages_*` generated from NQ only trained model. The performance on the Trivia dataset is lower than that in the paper:

Top-20: 72.8 / 69.0
Top-100: 81.3 / 78.7

The retriever results you provided in #35 are similar to those in the paper tho:
Top-20: 80.2
Top-100: 84.8

@vaibhavad Let me know what's the result on your end :)

**Comment by vlad-karpukhin** [comment]
Hello,

So you used NQ and multi set trained models on NQ only emebddings?
Multiset model chekpoint should not be used with other embeddings since
they were not trained together
We didn't evaluate NQ only model for Trivia, there is no such combination
in the paper. Trivia was evaluated for Trivia only and multiset model.
If the numbers you provided above are for NQ only checkpoint, then it is
quite expected the numbers are 2-3 point lower then multiset or
trivia-trained model.

**Comment by morningmoni** [comment]
Thanks for the prompt reply! 

I see. So in order to reproduce the results on Trivia, the easiest way for now is to re-generate multiset embeddings using the provided multiset model and then conduct retrieval using the multiset model, right? (I thought you meant NQ-only performed similarly on Trivia when saying "(multiset has) basically same performance as NQ only trained mode"

**Comment by vlad-karpukhin** [comment]
Yes,
you only need to generate embeddings using multiset embeddings.
I know this is quite an expensive process. If you can wait till the end of
current week, I will provide those.

**Comment by morningmoni** [comment]
I'd appreciate your help!
