### ISSUE TITLE
Request for sharing CuratedTREC dataset

### ISSUE THREAD

**Issue by vikas95** [facebookresearch/DPR#76]
Hi,

Thanks a lot for sharing the DPR resources. We could download the other datasets mentioned in the paper except CuratedTREC. I wanted to request if you could share the CuratedTREC dataset (or the link).

We will be citing the original CuratedTREC paper (Baudisˇ and Sedivy` , 2015) upon use of the dataset in our evaluations. 

Thanks.

**Comment by vlad-karpukhin** [comment]
Hi Vikas,
Unfortunately, we are not providing CuratedTREC dataset since we had some special handling of this dataset which we don't provide in our code repository.
There is nothing hacky, we just don't have time to provide and code support and thus don't provide dataset which is not 100% compatible with our code base.
